on:
  schedule:
  - cron: '30 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CHeckout Moshidon Repo
      uses: actions/checkout@v3
      with:
        repository: LucasGGamerM/moshidon
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'nightly_keystore.jks'  
        fileDir: './mastodon/keystore/'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Build with Gradle
      run: ./gradlew assembleNightly
      env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          CURRENT_DATE: ${{ steps.date.outputs.date }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
       name: moshidon-nightly.apk
       path: ./mastodon/build/outputs/apk/nightly/moshidon-nightly.apk

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_TOKEN }}"
        automatic_release_tag: nightly-${{ steps.date.outputs.date }}
        title: Nightly ${{ steps.date.outputs.date }}
        prerelease: false
        files: |
          ./mastodon/build/outputs/apk/nightly/moshidon-nightly.apk
